export type ContentBlock =
  | { type: 'p'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'h3'; text: string }
  | { type: 'ul'; items: string[] }
  | { type: 'ol'; items: string[] }
  | { type: 'tip'; text: string }
  | { type: 'info'; text: string }
  | { type: 'table'; headers: string[]; rows: string[][] }

export interface BlogPostData {
  slug: string
  emoji: string
  featured: boolean
  date: string
  title: { en: string; hi: string }
  excerpt: { en: string; hi: string }
  category: { en: string; hi: string }
  readTime: { en: string; hi: string }
  content: { en: ContentBlock[]; hi: ContentBlock[] }
}

export const BLOG_POSTS: BlogPostData[] = [
  {
    slug: 'best-time-to-visit-mathura-vrindavan',
    emoji: '🗓️',
    featured: true,
    date: 'January 15, 2025',
    title: {
      en: 'Best Time to Visit Mathura and Vrindavan',
      hi: 'मथुरा और वृन्दावन जाने का सबसे अच्छा समय',
    },
    excerpt: {
      en: 'October to March is perfect — pleasant weather, clear skies, and peaceful darshan. Here is a month-by-month guide to help you plan.',
      hi: 'अक्टूबर से मार्च का समय सबसे उत्तम है — सुहावना मौसम, साफ आकाश और शांतिपूर्ण दर्शन। माह-दर-माह गाइड से अपनी यात्रा की योजना बनाएं।',
    },
    category: { en: 'Travel Guide', hi: 'यात्रा गाइड' },
    readTime: { en: '5 min read', hi: '5 मिनट पढ़ें' },
    content: {
      en: [
        { type: 'p', text: 'Mathura and Vrindavan can be visited year-round, but the experience varies dramatically by season. The right timing can mean the difference between a serene pilgrimage and an uncomfortable ordeal.' },
        { type: 'h2', text: 'The Best Season: October to March' },
        { type: 'p', text: 'Winter is peak season for good reason. Temperatures hover between 8°C and 25°C, making walking between temples pleasant. The air is clean, morning aartis are crisp and atmospheric, and crowds are manageable except during major festivals.' },
        { type: 'table', headers: ['Month', 'Temp (°C)', 'Crowd Level', 'Highlights'], rows: [
          ['October', '18–30', 'Medium', 'Post-monsoon greenery, Diwali in Braj'],
          ['November', '12–26', 'Low–Medium', 'Peaceful darshan, Govardhan Puja'],
          ['December', '8–22', 'Medium', 'Winter aartis, clear mornings'],
          ['January', '6–18', 'Low–Medium', 'Sankranti kite festival, makar snan'],
          ['February', '10–24', 'High', 'Holi season begins in Barsana'],
          ['March', '14–30', 'Very High', 'Holi — the biggest festival'],
        ]},
        { type: 'h2', text: 'April to June: Avoid If Possible' },
        { type: 'p', text: 'Summers are brutal. May temperatures frequently cross 45°C. The white marble of Prem Mandir becomes too hot to stand on barefoot. Most pilgrim groups avoid this period entirely.' },
        { type: 'tip', text: 'If you must visit in summer, restrict temple visits to before 9 AM and after 5 PM. Carry a water bottle, wear light cotton, and use the Yamuna riverside ghats for shade.' },
        { type: 'h2', text: 'July to September: Monsoon Magic' },
        { type: 'p', text: 'Monsoon transforms Braj into lush greenery. Janmashtami (August) falls in this season and draws millions to Mathura. The humidity is high and travel can be disrupted by rain, but the festival energy is unmatched.' },
        { type: 'info', text: 'Janmashtami 2025 falls on August 16. Book accommodation at least 2–3 months in advance if you plan to attend.' },
        { type: 'h2', text: 'Festival Calendar Quick Reference' },
        { type: 'ul', items: [
          'Holi: March (Barsana Lathmar — 10 days before Holi; Vrindavan Phoolon Ki Holi — 1 week before)',
          'Janmashtami: August (midnight celebration at Krishna Janmabhoomi)',
          'Radhashtami: September (Radhakund special events)',
          'Diwali & Govardhan Puja: October/November',
          'Mathura Kumbh (Kartik Purnima): November (Vishram Ghat snan)',
        ]},
        { type: 'h2', text: 'Practical Tips by Season' },
        { type: 'ul', items: [
          'Winter mornings (Dec–Jan): carry a light shawl for early aartis at Vishram Ghat',
          'Festival periods: book trains and hotels 60–90 days ahead',
          'Summer: visit only on weekdays to avoid school-group crowds',
          'Monsoon: keep a rain poncho; roads near Yamuna flood occasionally',
        ]},
      ],
      hi: [
        { type: 'p', text: 'मथुरा और वृन्दावन पूरे वर्ष जाया जा सकता है, लेकिन अनुभव मौसम के अनुसार बहुत अलग होता है। सही समय पर जाने से शांतिपूर्ण तीर्थयात्रा और असुविधाजनक यात्रा में फर्क होता है।' },
        { type: 'h2', text: 'सबसे अच्छा मौसम: अक्टूबर से मार्च' },
        { type: 'p', text: 'सर्दी का मौसम पीक सीजन है और इसका कारण स्पष्ट है। तापमान 8°C से 25°C के बीच रहता है, जिससे मंदिरों के बीच पैदल चलना सुखद होता है। हवा साफ रहती है, सुबह की आरतियाँ ताज़गी भरी होती हैं और बड़े उत्सवों को छोड़कर भीड़ नियंत्रित रहती है।' },
        { type: 'table', headers: ['माह', 'तापमान (°C)', 'भीड़ स्तर', 'विशेषताएं'], rows: [
          ['अक्टूबर', '18–30', 'मध्यम', 'मानसून के बाद हरियाली, ब्रज में दीपावली'],
          ['नवंबर', '12–26', 'कम–मध्यम', 'शांतिपूर्ण दर्शन, गोवर्धन पूजा'],
          ['दिसंबर', '8–22', 'मध्यम', 'शीतकालीन आरतियाँ, साफ सुबहें'],
          ['जनवरी', '6–18', 'कम–मध्यम', 'संक्रांति पतंग उत्सव, मकर स्नान'],
          ['फरवरी', '10–24', 'अधिक', 'बरसाना में होली सीजन शुरू'],
          ['मार्च', '14–30', 'बहुत अधिक', 'होली — सबसे बड़ा उत्सव'],
        ]},
        { type: 'h2', text: 'अप्रैल से जून: यदि संभव हो तो बचें' },
        { type: 'p', text: 'गर्मी बहुत कठोर होती है। मई में तापमान अक्सर 45°C से अधिक हो जाता है। प्रेम मंदिर का सफेद संगमरमर नंगे पैर खड़े होने के लिए बहुत गर्म हो जाता है। अधिकांश तीर्थयात्री समूह इस अवधि से बचते हैं।' },
        { type: 'tip', text: 'यदि आपको गर्मियों में जाना ही हो, तो मंदिर दर्शन सुबह 9 बजे से पहले और शाम 5 बजे के बाद तक सीमित रखें। पानी की बोतल साथ रखें, हल्के सूती कपड़े पहनें।' },
        { type: 'h2', text: 'जुलाई से सितंबर: मानसून का जादू' },
        { type: 'p', text: 'मानसून ब्रज को हरी-भरी हरियाली में बदल देता है। जन्माष्टमी (अगस्त) इसी मौसम में पड़ती है और लाखों श्रद्धालुओं को मथुरा खींच लाती है।' },
        { type: 'info', text: 'जन्माष्टमी 2025: 16 अगस्त। यदि आप उत्सव में भाग लेना चाहते हैं तो 2–3 महीने पहले आवास बुक करें।' },
        { type: 'h2', text: 'उत्सव कैलेंडर संक्षिप्त संदर्भ' },
        { type: 'ul', items: [
          'होली: मार्च (बरसाना लठमार — होली से 10 दिन पहले; वृन्दावन फूलों की होली — 1 सप्ताह पहले)',
          'जन्माष्टमी: अगस्त (कृष्ण जन्मभूमि पर मध्यरात्रि उत्सव)',
          'राधाष्टमी: सितंबर (राधाकुंड विशेष कार्यक्रम)',
          'दीपावली और गोवर्धन पूजा: अक्टूबर/नवंबर',
          'कार्तिक पूर्णिमा मथुरा: नवंबर (विश्राम घाट स्नान)',
        ]},
        { type: 'h2', text: 'मौसम के अनुसार व्यावहारिक सुझाव' },
        { type: 'ul', items: [
          'सर्दी की सुबह (दिसंबर–जनवरी): विश्राम घाट पर सुबह की आरतियों के लिए हल्का शॉल साथ लें',
          'उत्सव काल: ट्रेन और होटल 60–90 दिन पहले बुक करें',
          'गर्मी: स्कूल-समूह की भीड़ से बचने के लिए केवल सप्ताह के दिनों में जाएं',
          'मानसून: रेन पोंचो रखें; यमुना के पास सड़कें कभी-कभी बाढ़ग्रस्त होती हैं',
        ]},
      ],
    },
  },
  {
    slug: 'complete-mathura-vrindavan-temples-guide',
    emoji: '🛕',
    featured: true,
    date: 'December 10, 2024',
    title: {
      en: 'Complete Guide to 20 Must-Visit Temples in Mathura Vrindavan',
      hi: 'मथुरा वृन्दावन के 20 प्रमुख मंदिरों की संपूर्ण गाइड',
    },
    excerpt: {
      en: 'From Krishna Janmabhoomi to Prem Mandir — timings, significance, and practical tips for visiting every major temple in Braj.',
      hi: 'कृष्ण जन्मभूमि से प्रेम मंदिर तक — ब्रज के हर प्रमुख मंदिर की समय-सारणी, महत्व और व्यावहारिक सुझाव।',
    },
    category: { en: 'Temple Guide', hi: 'मंदिर गाइड' },
    readTime: { en: '12 min read', hi: '12 मिनट पढ़ें' },
    content: {
      en: [
        { type: 'p', text: 'Braj Mandal contains over 5,000 temples, but these 20 are the ones every pilgrim should visit. We have organised them by location — Mathura first, then Vrindavan — so you can plan an efficient route.' },
        { type: 'h2', text: 'Mathura — The Birthplace' },
        { type: 'h3', text: '1. Krishna Janmabhoomi' },
        { type: 'ul', items: [
          'Location: Mathura city centre, near Shahi Eid Gah Mosque',
          'Timings: 6:00 AM – 12:00 PM, 4:00 PM – 9:30 PM (check seasonally)',
          'Significance: The exact prison cell (Garbha Griha) where Krishna was born',
          'Tip: Visit early morning for crowd-free darshan; security check takes 10–15 min',
        ]},
        { type: 'h3', text: '2. Dwarkadhish Temple' },
        { type: 'ul', items: [
          'Location: Vishram Ghat area, Mathura',
          'Timings: 6:30 AM – 12:00 PM, 5:00 PM – 9:00 PM',
          'Significance: 18th-century temple with stunning Rajasthani architecture; dedicated to Lord Dwarka',
          'Tip: Attend the evening aarti for an incredible crowd energy experience',
        ]},
        { type: 'h3', text: '3. Vishram Ghat' },
        { type: 'ul', items: [
          'Location: Yamuna riverbank, Mathura',
          'Best time: Sunrise (5:30–7:00 AM) or sunset aarti (6:30 PM in winter)',
          'Significance: Krishna rested here after defeating Kansa; 25 ghats along the river',
          'Tip: Take a boat ride from here — ₹50–100 per person for 20 minutes',
        ]},
        { type: 'h3', text: '4. Govind Dev Temple, Mathura' },
        { type: 'ul', items: [
          'Location: Near Rangeshwar Mahadev, old Mathura',
          'Significance: Ancient temple; idol later moved to Jaipur City Palace (the Govind Dev Ji there)',
        ]},
        { type: 'h2', text: 'Vrindavan — The Forest of Love' },
        { type: 'h3', text: '5. Banke Bihari Temple' },
        { type: 'ul', items: [
          'Location: Loi Bazaar, Vrindavan',
          'Timings: 7:45 AM – 12:00 PM, 5:30 PM – 9:30 PM (summer hours differ)',
          'Significance: The most beloved temple in Vrindavan; Swami Haridas\'s deity',
          'Tip: No bells, no conch — the curtain opens and closes every few seconds to avoid devotees fainting from Bihari Ji\'s beauty',
        ]},
        { type: 'h3', text: '6. Prem Mandir' },
        { type: 'ul', items: [
          'Location: Raman Reti, Vrindavan (opposite ISKCON)',
          'Timings: 8:30 AM – 12:00 PM, 4:30 PM – 8:30 PM',
          'Light show: 7:00 PM – 8:30 PM daily',
          'Significance: Built by Jagadguru Kripalu Maharaj; Italian marble carvings depict Krishna\'s entire life',
          'Tip: The light-and-music show in the evening is free and spectacular — do not miss it',
        ]},
        { type: 'h3', text: '7. ISKCON Vrindavan (Sri Krishna Balarama Mandir)' },
        { type: 'ul', items: [
          'Location: Bhaktivedanta Swami Marg, Raman Reti',
          'Timings: 4:30 AM – 8:30 PM (aartis every 2–3 hours)',
          'Significance: Founded by Srila Prabhupada; attracts international devotees',
          'Tip: Attend the Mangala aarti at 4:30 AM for the most devotional atmosphere',
        ]},
        { type: 'h3', text: '8. Radha Raman Temple' },
        { type: 'ul', items: [
          'Location: Old Vrindavan',
          'Timings: 8:00 AM – 12:30 PM, 5:00 PM – 8:30 PM',
          'Significance: One of the oldest active temples in Vrindavan (1542 CE); original deity never sent to Jaipur',
          'Tip: The priests here are descendants of Gopal Bhatt Goswami — very knowledgeable about Vaishnava traditions',
        ]},
        { type: 'h3', text: '9. Radha Damodar Temple' },
        { type: 'ul', items: [
          'Location: Near Seva Kunj, Vrindavan',
          'Timings: 6:00 AM – 12:00 PM, 4:00 PM – 8:30 PM',
          'Significance: Srila Prabhupada lived and wrote several books in the rooms here',
          'Tip: Prabhupada\'s rooms are preserved as a small museum — request entry from the office',
        ]},
        { type: 'h3', text: '10. Madan Mohan Temple' },
        { type: 'ul', items: [
          'Location: Yamuna riverside, old Vrindavan town',
          'Timings: 6:30 AM – 12:00 PM, 5:00 PM – 8:00 PM',
          'Significance: One of the seven Goswami temples; believed to be built in 16th century by Sanatana Goswami',
        ]},
        { type: 'h3', text: '11. Govind Dev Temple, Vrindavan' },
        { type: 'ul', items: [
          'Location: Govind Ghera, Vrindavan',
          'Timings: 4:30 AM – 12:00 PM, 4:00 PM – 9:00 PM',
          'Significance: The largest and most architecturally grand of the Goswami temples; Akbar\'s builder helped construct it',
        ]},
        { type: 'h2', text: 'Around Braj' },
        { type: 'h3', text: '12–20. Other Essential Temples' },
        { type: 'ul', items: [
          'Katyayani Devi (Vrindavan) — Shakti shrine, important for unmarried women',
          'Radhakund & Shyamkund (Govardhan) — Twin sacred ponds, extremely holy',
          'Kusum Sarovar (Govardhan) — Beautiful lake with ghats and peacocks',
          'Nandagram — Lord Nanda\'s village, birthplace energy',
          'Barsana — Radharani\'s birthplace, stunning hilltop temple',
          'Gokul Mathura — Where infant Krishna was taken by Vasudeva',
          'Vrinda Devi Temple (Vrindavan) — Forest goddess; small but deeply atmospheric',
          'Shahji Temple (Vrindavan) — Known for the famous Basanti Kamra (yellow room)',
          'Jaipur Temple, Vrindavan — Modern, richly decorated',
        ]},
        { type: 'tip', text: 'Plan temples in two half-day blocks: Mathura in the morning (8 AM–1 PM), Vrindavan in the afternoon and evening (3 PM–8 PM). Avoid major temples during midday puja breaks (12 PM–4 PM).' },
      ],
      hi: [
        { type: 'p', text: 'ब्रज मंडल में 5,000 से अधिक मंदिर हैं, लेकिन ये 20 वो हैं जो हर तीर्थयात्री को अवश्य देखने चाहिए। हमने इन्हें स्थान के अनुसार व्यवस्थित किया है — पहले मथुरा, फिर वृन्दावन।' },
        { type: 'h2', text: 'मथुरा — जन्मभूमि' },
        { type: 'h3', text: '1. कृष्ण जन्मभूमि' },
        { type: 'ul', items: [
          'स्थान: मथुरा शहर केंद्र, शाही ईदगाह मस्जिद के पास',
          'समय: सुबह 6:00 – दोपहर 12:00, शाम 4:00 – रात 9:30',
          'महत्व: वह कारागृह (गर्भ गृह) जहाँ कृष्ण का जन्म हुआ था',
          'सुझाव: भीड़-मुक्त दर्शन के लिए सुबह जल्दी जाएं; सुरक्षा जांच में 10–15 मिनट लगते हैं',
        ]},
        { type: 'h3', text: '2. द्वारकाधीश मंदिर' },
        { type: 'ul', items: [
          'स्थान: विश्राम घाट क्षेत्र, मथुरा',
          'समय: सुबह 6:30 – दोपहर 12:00, शाम 5:00 – रात 9:00',
          'महत्व: 18वीं सदी का मंदिर, शानदार राजस्थानी वास्तुकला',
          'सुझाव: संध्या आरती में अविश्वसनीय भक्ति अनुभव के लिए अवश्य जाएं',
        ]},
        { type: 'h3', text: '3. विश्राम घाट' },
        { type: 'ul', items: [
          'स्थान: यमुना तट, मथुरा',
          'सर्वोत्तम समय: सूर्योदय (5:30–7:00 AM) या संध्या आरती (शीतकाल में 6:30 PM)',
          'महत्व: कंस वध के बाद कृष्ण यहाँ विश्राम किए थे; नदी के किनारे 25 घाट',
          'सुझाव: यहाँ से नाव की सवारी करें — 20 मिनट के लिए ₹50–100 प्रति व्यक्ति',
        ]},
        { type: 'h2', text: 'वृन्दावन — प्रेम की वन' },
        { type: 'h3', text: '5. बाँके बिहारी मंदिर' },
        { type: 'ul', items: [
          'स्थान: लोई बाज़ार, वृन्दावन',
          'समय: सुबह 7:45 – दोपहर 12:00, शाम 5:30 – रात 9:30',
          'महत्व: वृन्दावन का सबसे प्रिय मंदिर; स्वामी हरिदास के आराध्य',
          'सुझाव: यहाँ कोई घंटी या शंख नहीं बजाई जाती — पर्दा हर कुछ सेकंड में खुलता-बंद होता है',
        ]},
        { type: 'h3', text: '6. प्रेम मंदिर' },
        { type: 'ul', items: [
          'स्थान: रमण रेती, वृन्दावन (ISKCON के सामने)',
          'समय: सुबह 8:30 – दोपहर 12:00, शाम 4:30 – रात 8:30',
          'लाइट शो: शाम 7:00 – रात 8:30 (प्रतिदिन)',
          'महत्व: जगद्गुरु कृपालु महाराज द्वारा निर्मित; इतालवी संगमरमर पर कृष्ण जीवन के दृश्य',
          'सुझाव: संध्या लाइट-एंड-म्यूजिक शो निःशुल्क है और अत्यंत शानदार है',
        ]},
        { type: 'h3', text: '7. ISKCON वृन्दावन (श्री कृष्ण बलराम मंदिर)' },
        { type: 'ul', items: [
          'स्थान: भक्तिवेदांत स्वामी मार्ग, रमण रेती',
          'समय: सुबह 4:30 – रात 8:30 (हर 2–3 घंटे में आरती)',
          'महत्व: श्रील प्रभुपाद द्वारा स्थापित; अंतर्राष्ट्रीय भक्तों को आकर्षित करता है',
          'सुझाव: सुबह 4:30 बजे मंगला आरती में सर्वाधिक भक्तिमय वातावरण होता है',
        ]},
        { type: 'h3', text: '8. राधा रमण मंदिर' },
        { type: 'ul', items: [
          'स्थान: पुराना वृन्दावन',
          'समय: सुबह 8:00 – दोपहर 12:30, शाम 5:00 – रात 8:30',
          'महत्व: वृन्दावन के सबसे पुराने सक्रिय मंदिरों में से एक (1542 ई.); मूल विग्रह कभी जयपुर नहीं भेजा गया',
        ]},
        { type: 'h2', text: 'ब्रज के अन्य महत्वपूर्ण मंदिर' },
        { type: 'ul', items: [
          'राधाकुंड और श्यामकुंड (गोवर्धन) — जुड़वाँ पवित्र तालाब',
          'कुसुम सरोवर (गोवर्धन) — सुंदर झील, मोर और घाट',
          'नंदग्राम — नंद बाबा का गाँव',
          'बरसाना — राधारानी की जन्मभूमि, पहाड़ी पर भव्य मंदिर',
          'गोकुल मथुरा — जहाँ वासुदेव शिशु कृष्ण को ले गए थे',
          'वृंदा देवी मंदिर, वृन्दावन — वन की देवी का छोटा किन्तु पवित्र मंदिर',
        ]},
        { type: 'tip', text: 'मंदिरों की यात्रा दो आधे दिन की पालियों में करें: सुबह मथुरा (8 AM–1 PM), दोपहर और शाम वृन्दावन (3 PM–8 PM)। दोपहर पूजा विराम (12 PM–4 PM) के दौरान बड़े मंदिरों से बचें।' },
      ],
    },
  },
  {
    slug: 'govardhan-parikrama-complete-guide',
    emoji: '⛰️',
    featured: false,
    date: 'November 22, 2024',
    title: {
      en: "Govardhan Parikrama — The Complete Pilgrim's Guide",
      hi: 'गोवर्धन परिक्रमा — संपूर्ण तीर्थयात्री गाइड',
    },
    excerpt: {
      en: 'Everything about the sacred 21 km circumambulation — route, stops, best time, e-rickshaw options, and what to expect.',
      hi: 'पवित्र 21 किमी परिक्रमा के बारे में सब कुछ — मार्ग, पड़ाव, सर्वोत्तम समय, ई-रिक्शा विकल्प और क्या उम्मीद करें।',
    },
    category: { en: 'Pilgrimage', hi: 'तीर्थयात्रा' },
    readTime: { en: '8 min read', hi: '8 मिनट पढ़ें' },
    content: {
      en: [
        { type: 'p', text: 'Govardhan Parikrama is one of the most sacred acts a devotee can perform in Braj. The 21 km circumambulation of Govardhan Hill is walked barefoot by millions each year, completing either in a single stretch or over two days.' },
        { type: 'h2', text: 'The Route' },
        { type: 'p', text: 'The parikrama starts and ends at Jatipura (near Dan Ghati Mandir or Mukut Mukharvind). The circuit runs anti-clockwise (south first, toward Radhakund, then returning via Mansi Ganga).' },
        { type: 'ol', items: [
          'Jatipura / Dan Ghati Mandir — Starting point; large Krishna temple',
          'Punchari Ka Lota — Believed to be site of Krishna\'s leela (4 km)',
          'Radhakund & Shyamkund — Twin sacred ponds, the spiritual heart of the parikrama (8 km)',
          'Kusum Sarovar — Beautiful step-well and gardens (10 km)',
          'Govind Kund — Sacred pond (12 km)',
          'Mansi Ganga — Holy lake where Krishna held Govardhan on his pinky finger (15 km)',
          'Mukut Mukharvind — Govardhan\'s "face" — the holiest point on the hill (18 km)',
          'Return to Jatipura (21 km)',
        ]},
        { type: 'h2', text: 'How Long Does It Take?' },
        { type: 'table', headers: ['Mode', 'Time', 'Cost', 'Notes'], rows: [
          ['On foot', '5–7 hours', 'Free', 'Most meritorious; bring water and snacks'],
          ['On foot (dandavat)', '2–3 days', 'Free', 'Prostrating full-body every step; very advanced'],
          ['E-rickshaw', '2–3 hours', '₹150–200/person', 'Stops at major points; comfortable'],
          ['Cycle rickshaw', '3–4 hours', '₹100–150/person', 'Slower, more stops possible'],
        ]},
        { type: 'h2', text: 'Best Time to Do the Parikrama' },
        { type: 'ul', items: [
          'Early morning (5:30 AM start) in winter — cool, atmospheric, avoid afternoon heat',
          'Kartik month (Oct–Nov) — considered most auspicious; Govardhan Puja day (after Diwali) sees 200,000+ pilgrims',
          'Avoid: summer afternoons (unbearable heat), Monsoon (slippery paths near ghats)',
          'Ekadashi days — extra auspicious; more devotional chanting groups (bhajan mandalis)',
        ]},
        { type: 'h2', text: 'Practical Tips' },
        { type: 'ul', items: [
          'Go barefoot — footwear is not allowed on most of the path (shoe stands available at major stops)',
          'Carry: 1.5L water, light snacks, small bag for shoes, cash for prasad',
          'Dress code: traditional attire preferred; avoid shorts and sleeveless',
          'Toilets available at Radhakund, Kusum Sarovar, and Mansi Ganga',
          'First-aid: minor injuries from stones; wear thick socks under bare feet if sensitive',
        ]},
        { type: 'tip', text: 'Hire a local guide from Govardhan town (₹300–500) for the full parikrama. They know all the smaller shrines along the route and can explain the significance of each stop.' },
        { type: 'h2', text: 'Special Parikramas' },
        { type: 'ul', items: [
          'Govardhan Puja Parikrama (after Diwali) — biggest single-day parikrama event',
          'Kartik Parikrama (full month of Kartik) — most devotees complete multiple rounds',
          'Annakut (day after Govardhan Puja) — 56 food items (chhappan bhog) offered at the hill',
        ]},
      ],
      hi: [
        { type: 'p', text: 'गोवर्धन परिक्रमा ब्रज में एक भक्त द्वारा किए जाने वाले सबसे पवित्र कार्यों में से एक है। प्रतिवर्ष लाखों भक्त गोवर्धन पर्वत की 21 किमी परिक्रमा नंगे पैर करते हैं।' },
        { type: 'h2', text: 'मार्ग' },
        { type: 'p', text: 'परिक्रमा जतीपुरा (दान घाटी मंदिर या मुकुट मुखारविंद के पास) से शुरू और समाप्त होती है। परिक्रमा वामावर्त (दक्षिण पहले, राधाकुंड की ओर, फिर मानसी गंगा से वापस) चलती है।' },
        { type: 'ol', items: [
          'जतीपुरा / दान घाटी मंदिर — आरंभ स्थान; बड़ा कृष्ण मंदिर',
          'पुंछरी का लोटा — कृष्ण लीला का स्थान माना जाता है (4 किमी)',
          'राधाकुंड और श्यामकुंड — जुड़वाँ पवित्र तालाब, परिक्रमा का आध्यात्मिक केंद्र (8 किमी)',
          'कुसुम सरोवर — सुंदर बावड़ी और उद्यान (10 किमी)',
          'गोविंद कुंड — पवित्र तालाब (12 किमी)',
          'मानसी गंगा — पवित्र झील (15 किमी)',
          'मुकुट मुखारविंद — गोवर्धन का "मुख" — पर्वत का सबसे पवित्र बिंदु (18 किमी)',
          'जतीपुरा वापसी (21 किमी)',
        ]},
        { type: 'h2', text: 'कितना समय लगता है?' },
        { type: 'table', headers: ['माध्यम', 'समय', 'लागत', 'टिप्पणी'], rows: [
          ['पैदल', '5–7 घंटे', 'निःशुल्क', 'सर्वाधिक पुण्यकारी; पानी और नाश्ता साथ लें'],
          ['दंडवत परिक्रमा', '2–3 दिन', 'निःशुल्क', 'हर कदम पूर्ण शरीर साष्टांग प्रणाम; बहुत उन्नत'],
          ['ई-रिक्शा', '2–3 घंटे', '₹150–200/व्यक्ति', 'प्रमुख स्थलों पर रुकता है; आरामदायक'],
          ['साइकिल रिक्शा', '3–4 घंटे', '₹100–150/व्यक्ति', 'धीमा, अधिक पड़ावों पर रुकना संभव'],
        ]},
        { type: 'h2', text: 'परिक्रमा का सर्वोत्तम समय' },
        { type: 'ul', items: [
          'सर्दियों में सुबह जल्दी (5:30 AM से शुरुआत) — ठंडी हवा, वातावरण भक्तिमय',
          'कार्तिक माह (अक्टूबर–नवंबर) — सबसे शुभ माना जाता है',
          'बचें: गर्मी की दोपहर (असहनीय गर्मी), मानसून (घाट के पास फिसलन)',
          'एकादशी के दिन — अतिरिक्त शुभ; अधिक भजन मंडलियाँ',
        ]},
        { type: 'h2', text: 'व्यावहारिक सुझाव' },
        { type: 'ul', items: [
          'नंगे पैर जाएं — अधिकांश मार्ग पर जूते नहीं पहने जाते',
          'साथ लाएं: 1.5 लीटर पानी, हल्का नाश्ता, जूतों के लिए छोटा थैला, प्रसाद के लिए नकद',
          'ड्रेस कोड: पारंपरिक वस्त्र पसंदीदा; शॉर्ट्स और बिना आस्तीन के कपड़े न पहनें',
          'राधाकुंड, कुसुम सरोवर और मानसी गंगा पर शौचालय उपलब्ध हैं',
        ]},
        { type: 'tip', text: 'गोवर्धन शहर से स्थानीय गाइड किराए पर लें (₹300–500) जो पूरी परिक्रमा के दौरान सभी छोटे मंदिरों और उनके महत्व की जानकारी देंगे।' },
      ],
    },
  },
  {
    slug: 'mathura-holi-festival-guide',
    emoji: '🎨',
    featured: true,
    date: 'October 5, 2024',
    title: {
      en: "Mathura Holi — The World's Most Colourful Festival Guide",
      hi: 'मथुरा होली — विश्व के सबसे रंगीन उत्सव की संपूर्ण गाइड',
    },
    excerpt: {
      en: 'Barsana Lathmar Holi, Vrindavan Phoolon Ki Holi, and Mathura Holi — dates, locations, and how to experience each one safely.',
      hi: 'बरसाना लठमार होली, वृन्दावन फूलों की होली और मथुरा होली — तारीखें, स्थान और प्रत्येक उत्सव को सुरक्षित तरीके से अनुभव करें।',
    },
    category: { en: 'Festivals', hi: 'त्यौहार' },
    readTime: { en: '7 min read', hi: '7 मिनट पढ़ें' },
    content: {
      en: [
        { type: 'p', text: 'Holi in Braj is not one event — it is a ten-day celebration spread across different towns, each with its own unique tradition. The world-famous Lathmar Holi of Barsana, the flower Holi of Vrindavan, and the main colour festival of Mathura are all distinct experiences.' },
        { type: 'h2', text: '2025 Holi Festival Dates' },
        { type: 'table', headers: ['Event', 'Location', 'Date (2025)', 'Tradition'], rows: [
          ['Phoolon Ki Holi', 'Banke Bihari Temple, Vrindavan', 'March 3, 2025', 'Flower petals thrown from above; the first Holi of the season'],
          ['Lathmar Holi (Day 1)', 'Barsana', 'March 8, 2025', 'Women beat men with lathis (decorated sticks); men hold shields'],
          ['Lathmar Holi (Day 2)', 'Nandagram', 'March 9, 2025', 'Nandagram men "retaliate" with colour — the reverse Holi'],
          ['Widow Holi', 'Pagal Baba Ashram, Vrindavan', 'March 12, 2025', 'Widows celebrate Holi — a modern movement breaking tradition'],
          ['Rangbhari Ekadashi', 'Vishwanath Temple, Vrindavan', 'March 12, 2025', 'Shiva and Parvati play Holi; procession with gulal'],
          ['Vrindavan Holi', 'Banke Bihari & streets', 'March 13, 2025', 'Main street colour celebrations in Vrindavan'],
          ['Mathura Main Holi', 'Vishram Ghat & city', 'March 14, 2025', 'Main Holi; Holika Dahan the night before'],
          ['Dwarka Holi', 'Dwarkadhish Temple', 'March 15, 2025', 'Post-Holi colour play; more relaxed, family-friendly'],
        ]},
        { type: 'h2', text: 'Lathmar Holi at Barsana — What to Expect' },
        { type: 'p', text: 'Barsana Lathmar Holi is the flagship event. The legend: the men of Nandagram (Krishna\'s village) come to Barsana (Radha\'s village) to tease the women, and the women chase them with lathis.' },
        { type: 'ul', items: [
          'Venue: Shri Radhika Mandir (Shriji Temple) on the hilltop — most photogenic',
          'Timing: Activities begin from 10 AM; main Lathmar starts around 1–2 PM',
          'What to wear: Old clothes you don\'t mind getting stained; secure shoes',
          'Security: Cordons separate participants from spectators; stick to spectator areas',
          'Photography: Allowed from designated areas; protect camera from colour',
        ]},
        { type: 'h2', text: 'Phoolon Ki Holi at Banke Bihari' },
        { type: 'p', text: 'One week before the main Holi, priests at Banke Bihari Temple shower pilgrims with flower petals from above. It is enchanting and one of the most photographed moments of the Holi season.' },
        { type: 'info', text: 'Entry to Phoolon Ki Holi at Banke Bihari is free but the temple becomes very crowded by 10 AM. Arrive by 8:30 AM to get a good position inside.' },
        { type: 'h2', text: 'Safety and Practical Tips' },
        { type: 'ul', items: [
          'Colour: Use herbal/natural colour (gulal); avoid synthetic colour which can cause skin irritation',
          'Protect: Cover eyes with sunglasses, apply coconut oil to skin and hair before attending',
          'Valuables: Leave expensive jewellery at the hotel; use a waterproof pouch for phone',
          'Solo women: Join a guided group or go with a mixed group; avoid isolated lanes during celebrations',
          'Getting there: Book a car or taxi in advance — public transport is severely overcrowded during Holi',
          'Accommodation: Book 3–4 months in advance for Barsana/Mathura/Vrindavan during Holi week',
        ]},
        { type: 'tip', text: 'The most underrated experience: attend Mangala Aarti at Banke Bihari Temple the morning after main Holi. The temple is decorated with flowers and colour, the air smells of gulal, and there are very few tourists — a magical atmosphere.' },
      ],
      hi: [
        { type: 'p', text: 'ब्रज में होली एक उत्सव नहीं — यह दस दिनों का जश्न है जो विभिन्न शहरों में फैला है, प्रत्येक की अपनी अनूठी परंपरा है।' },
        { type: 'h2', text: '2025 होली उत्सव की तारीखें' },
        { type: 'table', headers: ['उत्सव', 'स्थान', 'तारीख (2025)', 'परंपरा'], rows: [
          ['फूलों की होली', 'बाँके बिहारी मंदिर, वृन्दावन', '3 मार्च 2025', 'ऊपर से फूलों की पंखुड़ियाँ बरसाई जाती हैं'],
          ['लठमार होली (दिन 1)', 'बरसाना', '8 मार्च 2025', 'महिलाएं लठियों से पुरुषों को मारती हैं; पुरुष ढाल लेकर बचाव करते हैं'],
          ['लठमार होली (दिन 2)', 'नंदग्राम', '9 मार्च 2025', 'नंदग्राम के पुरुष रंग से "प्रतिशोध" लेते हैं'],
          ['रंगभरी एकादशी', 'विश्वनाथ मंदिर, वृन्दावन', '12 मार्च 2025', 'शिव-पार्वती होली खेलते हैं; गुलाल के साथ शोभायात्रा'],
          ['वृन्दावन होली', 'बाँके बिहारी और गलियाँ', '13 मार्च 2025', 'मुख्य सड़क रंग समारोह'],
          ['मथुरा मुख्य होली', 'विश्राम घाट और शहर', '14 मार्च 2025', 'मुख्य होली; एक रात पहले होलिका दहन'],
        ]},
        { type: 'h2', text: 'बरसाना लठमार होली — क्या उम्मीद करें' },
        { type: 'p', text: 'बरसाना लठमार होली मुख्य आयोजन है। किंवदंती: नंदग्राम (कृष्ण के गाँव) के पुरुष बरसाना (राधा के गाँव) आते हैं महिलाओं को छेड़ने, और महिलाएं उन्हें लठियों से खदेड़ती हैं।' },
        { type: 'ul', items: [
          'स्थान: श्री राधिका मंदिर (श्रीजी मंदिर) पहाड़ी की चोटी पर — सबसे सुंदर दृश्य',
          'समय: गतिविधियाँ सुबह 10 बजे से शुरू; मुख्य लठमार दोपहर 1–2 बजे',
          'पहनावा: पुराने कपड़े जो दागदार हो सकें; मजबूत जूते',
          'सुरक्षा: दर्शकों और प्रतिभागियों को अलग करने वाले बैरिकेड; दर्शक क्षेत्र में ही रहें',
        ]},
        { type: 'h2', text: 'सुरक्षा और व्यावहारिक सुझाव' },
        { type: 'ul', items: [
          'रंग: हर्बल/प्राकृतिक रंग (गुलाल) का उपयोग करें; सिंथेटिक रंग से त्वचा में जलन हो सकती है',
          'सुरक्षा: आँखों पर धूप का चश्मा, त्वचा और बालों पर नारियल तेल लगाएं',
          'कीमती सामान: महंगे गहने होटल में छोड़ें; फोन के लिए वाटरप्रूफ पाउच',
          'आवास: होली सप्ताह के दौरान 3–4 महीने पहले बुकिंग करें',
        ]},
        { type: 'tip', text: 'सबसे कम सराही जाने वाला अनुभव: मुख्य होली के अगले दिन सुबह बाँके बिहारी मंदिर में मंगला आरती में जाएं। मंदिर फूलों और रंग से सजा होता है, बहुत कम पर्यटक होते हैं — एक जादुई वातावरण।' },
      ],
    },
  },
  {
    slug: 'janmashtami-mathura-guide',
    emoji: '🎉',
    featured: false,
    date: 'September 18, 2024',
    title: {
      en: "Janmashtami in Mathura — The Ultimate Experience Guide",
      hi: 'मथुरा में जन्माष्टमी — संपूर्ण अनुभव गाइड',
    },
    excerpt: {
      en: "Krishna's birthday is celebrated like nowhere else on Earth. Here's how to witness this spectacular festival in his birthplace.",
      hi: 'कृष्ण का जन्मदिन पृथ्वी पर और कहीं इस तरह नहीं मनाया जाता। उनकी जन्मभूमि में इस शानदार उत्सव को कैसे देखें।',
    },
    category: { en: 'Festivals', hi: 'त्यौहार' },
    readTime: { en: '6 min read', hi: '6 मिनट पढ़ें' },
    content: {
      en: [
        { type: 'p', text: 'Janmashtami — the birthday of Lord Krishna — is celebrated with unparalleled intensity in Mathura. The entire city transforms for 48 hours as millions of devotees descend on the birthplace of the divine cowherd.' },
        { type: 'info', text: 'Janmashtami 2025 falls on August 16 (Saturday). The midnight celebration (Nishita Puja) is the spiritual apex — Krishna was born at midnight.' },
        { type: 'h2', text: 'The 48-Hour Festival Timeline' },
        { type: 'table', headers: ['Time', 'Event', 'Location'], rows: [
          ['Aug 15, 6 PM', 'Phul Bangla decoration darshan opens', 'Krishna Janmabhoomi'],
          ['Aug 15, 8 PM onwards', 'Cultural programmes, bhajans, devotional music', 'Multiple temples & ghats'],
          ['Aug 16, 3 AM', 'Mangala Aarti — first aarti of Janmashtami day', 'Krishna Janmabhoomi'],
          ['Aug 16, all day', 'Fasting observed; special darshan queues', 'All major temples'],
          ['Aug 16, 9 PM', 'Jhankis (tableaux) of Krishna\'s life begin', 'Streets of Mathura'],
          ['Aug 16, 11 PM', 'Countdown begins at Janmabhoomi', 'Krishna Janmabhoomi inner sanctum'],
          ['Aug 16, 12:00 AM', 'Birth announced; abhishek, conch, aarti', 'Krishna Janmabhoomi'],
          ['Aug 17, 1–4 AM', 'Crowds continue; midnight darshan queues', 'All night'],
          ['Aug 17, 8 AM', 'Nandotsav — Krishna\'s birth celebrated in Nandagram', 'Nandagram village'],
        ]},
        { type: 'h2', text: 'Where to Experience Janmashtami' },
        { type: 'ul', items: [
          'Krishna Janmabhoomi — The main site; midnight abhishek is the centrepiece',
          'Dwarkadhish Temple — Spectacular decoration; aarti at midnight draws thousands',
          'ISKCON Vrindavan — International flavour; English commentary; well-organised',
          'Banke Bihari Temple — Unusually allows late-night darshan on Janmashtami',
          'Vishram Ghat — Yamuna aarti at midnight; diyas floating on the river',
        ]},
        { type: 'h2', text: 'VIP Darshan and Tickets' },
        { type: 'p', text: 'Krishna Janmabhoomi Trust offers VIP darshan passes for Janmashtami to avoid the general crowd (estimated 5–8 lakh visitors). VIP passes (₹1,500 in recent years) allow entry to the Garbha Griha area with timed slots.' },
        { type: 'tip', text: 'VIP darshan passes go on sale 30–45 days before Janmashtami via the official Janmabhoomi Trust website. They sell out within hours of going live. Set a reminder.' },
        { type: 'h2', text: 'Practical Preparation' },
        { type: 'ul', items: [
          'Accommodation: Book 3–4 months ahead; all Mathura and Vrindavan hotels fill by June',
          'Transport: Private car strongly recommended — local roads close to through-traffic near Janmabhoomi from midnight',
          'Food: Most restaurants and dhabas remain open all night; many offer free langar (community meals)',
          'What to wear: Comfortable, light clothes — August is hot and humid; avoid valuables in crowds',
          'Cash: ATMs run out at night; withdraw in advance',
          'Mobile network: Very congested — download offline maps, share location with travel companions',
        ]},
        { type: 'h2', text: 'Nandotsav — The Day After' },
        { type: 'p', text: 'The next day (Aug 17, 2025) is Nandotsav — the celebration of Krishna\'s birth in Gokul. The energy shifts from the divine birth to joyful celebration: Nand Baba distributes sweets, colour is thrown, and the mood is jubilant.' },
      ],
      hi: [
        { type: 'p', text: 'जन्माष्टमी — भगवान कृष्ण का जन्मदिन — मथुरा में अद्वितीय उत्साह के साथ मनाई जाती है। लाखों भक्तों के आगमन से पूरा शहर 48 घंटों के लिए बदल जाता है।' },
        { type: 'info', text: 'जन्माष्टमी 2025: 16 अगस्त (शनिवार)। मध्यरात्रि उत्सव (निशित पूजा) आध्यात्मिक चरमोत्कर्ष है — कृष्ण का जन्म मध्यरात्रि में हुआ था।' },
        { type: 'h2', text: '48 घंटे का उत्सव कार्यक्रम' },
        { type: 'table', headers: ['समय', 'कार्यक्रम', 'स्थान'], rows: [
          ['15 अगस्त, शाम 6 बजे', 'फूल बंगला सजावट दर्शन शुरू', 'कृष्ण जन्मभूमि'],
          ['15 अगस्त, रात 8 बजे से', 'सांस्कृतिक कार्यक्रम, भजन, भक्ति संगीत', 'कई मंदिर और घाट'],
          ['16 अगस्त, रात 3 बजे', 'मंगला आरती — जन्माष्टमी दिन की पहली आरती', 'कृष्ण जन्मभूमि'],
          ['16 अगस्त, पूरे दिन', 'उपवास; विशेष दर्शन कतारें', 'सभी प्रमुख मंदिर'],
          ['16 अगस्त, रात 12:00', 'जन्म की घोषणा; अभिषेक, शंख, आरती', 'कृष्ण जन्मभूमि'],
          ['17 अगस्त, सुबह 8 बजे', 'नंदोत्सव — नंदग्राम में जन्म का जश्न', 'नंदग्राम गाँव'],
        ]},
        { type: 'h2', text: 'जन्माष्टमी कहाँ अनुभव करें' },
        { type: 'ul', items: [
          'कृष्ण जन्मभूमि — मुख्य स्थल; मध्यरात्रि अभिषेक केंद्रबिंदु है',
          'द्वारकाधीश मंदिर — शानदार सजावट; मध्यरात्रि आरती हजारों को आकर्षित करती है',
          'ISKCON वृन्दावन — अंतर्राष्ट्रीय माहौल; सुव्यवस्थित',
          'विश्राम घाट — मध्यरात्रि यमुना आरती; नदी पर दीये तैरते हैं',
        ]},
        { type: 'h2', text: 'VIP दर्शन और टिकट' },
        { type: 'p', text: 'कृष्ण जन्मभूमि ट्रस्ट जन्माष्टमी के लिए VIP दर्शन पास प्रदान करता है (हाल के वर्षों में ₹1,500)। ये गर्भ गृह क्षेत्र में समयबद्ध प्रवेश देते हैं। जन्माष्टमी से 30–45 दिन पहले आधिकारिक वेबसाइट पर बिक्री शुरू होती है।' },
        { type: 'h2', text: 'व्यावहारिक तैयारी' },
        { type: 'ul', items: [
          'आवास: 3–4 महीने पहले बुकिंग करें; जून तक सभी होटल भर जाते हैं',
          'परिवहन: निजी कार की सिफारिश — मध्यरात्रि से जन्मभूमि के पास सड़कें बंद हो जाती हैं',
          'भोजन: अधिकांश रेस्तरां और ढाबे रात भर खुले रहते हैं; कई मुफ्त लंगर प्रदान करते हैं',
          'नकद: ATM रात को खाली हो जाते हैं; पहले निकाल लें',
        ]},
      ],
    },
  },
  {
    slug: 'mathura-vrindavan-one-day-itinerary',
    emoji: '📍',
    featured: false,
    date: 'August 30, 2024',
    title: {
      en: 'Perfect One Day Itinerary for Mathura and Vrindavan',
      hi: 'मथुरा और वृन्दावन के लिए एक दिन की परफेक्ट यात्रा योजना',
    },
    excerpt: {
      en: 'How to see the best of both cities in a single day — temple order, timings, lunch spots, and what to skip if time is short.',
      hi: 'एक दिन में दोनों शहरों का सर्वश्रेष्ठ कैसे देखें — मंदिर क्रम, समय, लंच स्थान और समय कम होने पर क्या छोड़ें।',
    },
    category: { en: 'Itinerary', hi: 'यात्रा क्रम' },
    readTime: { en: '6 min read', hi: '6 मिनट पढ़ें' },
    content: {
      en: [
        { type: 'p', text: 'A single day in Mathura–Vrindavan can be deeply fulfilling if you plan it right. The key: start early, hit Mathura in the morning, move to Vrindavan by afternoon, and catch the evening aarti before heading back.' },
        { type: 'h2', text: 'The Itinerary at a Glance' },
        { type: 'table', headers: ['Time', 'Activity', 'Duration'], rows: [
          ['5:30–6:00 AM', 'Arrive Mathura; check-in or freshen up', '30 min'],
          ['6:00–7:00 AM', 'Vishram Ghat sunrise aarti + boat ride on Yamuna', '1 hour'],
          ['7:00–8:30 AM', 'Krishna Janmabhoomi darshan', '90 min'],
          ['8:30–9:30 AM', 'Dwarkadhish Temple darshan', '1 hour'],
          ['9:30–10:00 AM', 'Breakfast at local dhaba near Vishram Ghat', '30 min'],
          ['10:00–11:00 AM', 'Drive / auto to Vrindavan (12 km)', '1 hour'],
          ['11:00 AM–12:30 PM', 'Banke Bihari Temple darshan', '90 min'],
          ['12:30–1:30 PM', 'Lunch at ISKCON prasad hall or Madhuvan Restaurant', '1 hour'],
          ['1:30–2:30 PM', 'Rest / hotel break (avoid peak heat)', '1 hour'],
          ['2:30–4:00 PM', 'Radha Raman or Radha Damodar Temple', '90 min'],
          ['4:00–5:30 PM', 'Prem Mandir — architecture and grounds', '90 min'],
          ['5:30–7:00 PM', 'ISKCON Temple aarti + Prem Mandir light show', '90 min'],
          ['7:00 PM', 'Dinner + depart', ''],
        ]},
        { type: 'h2', text: 'Morning: Mathura (5:30 AM – 10:00 AM)' },
        { type: 'p', text: 'Begin at Vishram Ghat at sunrise. The air is cool, bells are ringing across the ghats, and a short boat ride gives you the full panorama of the riverside temples. Walk to Krishna Janmabhoomi (10 minutes by foot from Vishram Ghat) — queues are shortest before 8 AM.' },
        { type: 'h3', text: 'Breakfast Recommendation' },
        { type: 'p', text: 'Brijwasi Mithai (near Dwarkadhish Temple): kachori-sabzi and rabri — the quintessential Mathura breakfast. Budget: ₹80–120 per person.' },
        { type: 'h2', text: 'Afternoon: Vrindavan (10:00 AM – 5:30 PM)' },
        { type: 'p', text: 'Take an auto-rickshaw or taxi to Vrindavan (₹150–250 from Mathura). Start at Banke Bihari — arrive before noon to avoid peak afternoon crowds. After lunch, the smaller temples (Radha Raman, Radha Damodar) are quieter and profoundly atmospheric.' },
        { type: 'h3', text: 'Lunch Recommendation' },
        { type: 'ul', items: [
          'ISKCON Vrindavan prasad hall: thali ₹120–180 (pure vegetarian)',
          'Madhuvan Restaurant (near Banke Bihari): North Indian thali, clean, air-conditioned',
          'Local puri-sabzi at Loi Bazaar: ₹60–80',
        ]},
        { type: 'h2', text: 'Evening: Aarti and Light Show (5:30 PM – 7:00 PM)' },
        { type: 'p', text: 'The ISKCON evening aarti (Sandhya Aarti, 6:30 PM) is one of the most spiritually charged moments in Vrindavan. From there, walk or auto to Prem Mandir for the free light-and-music show that starts at 7 PM.' },
        { type: 'h2', text: 'If Time Is Short — What to Skip' },
        { type: 'ul', items: [
          'Skip Govind Dev Temple if you\'re short on time — beautiful but similar to others',
          'Skip the boat ride if arriving late — spend that time at Janmabhoomi instead',
          'Skip Radha Damodar if fatigue sets in — Radha Raman is more unique',
          'Skip afternoon rest if it is winter — use that time for an extra temple',
        ]},
        { type: 'tip', text: 'Hire a local guide in Vrindavan (₹400–600 for half day) to navigate the narrow lanes and understand the mythology behind each temple. This transforms the experience from sightseeing to pilgrimage.' },
      ],
      hi: [
        { type: 'p', text: 'सही योजना के साथ मथुरा–वृन्दावन में एक दिन बहुत संतोषजनक हो सकता है। मुख्य बात: जल्दी शुरू करें, सुबह मथुरा, दोपहर वृन्दावन और शाम को आरती पकड़ें।' },
        { type: 'h2', text: 'एक नज़र में यात्रा क्रम' },
        { type: 'table', headers: ['समय', 'गतिविधि', 'अवधि'], rows: [
          ['5:30–6:00 AM', 'मथुरा पहुँचें; फ्रेश हों', '30 मिनट'],
          ['6:00–7:00 AM', 'विश्राम घाट सूर्योदय आरती + यमुना नाव यात्रा', '1 घंटा'],
          ['7:00–8:30 AM', 'कृष्ण जन्मभूमि दर्शन', '90 मिनट'],
          ['8:30–9:30 AM', 'द्वारकाधीश मंदिर दर्शन', '1 घंटा'],
          ['9:30–10:00 AM', 'विश्राम घाट के पास ढाबे पर नाश्ता', '30 मिनट'],
          ['10:00–11:00 AM', 'वृन्दावन ड्राइव/ऑटो (12 किमी)', '1 घंटा'],
          ['11:00 AM–12:30 PM', 'बाँके बिहारी मंदिर दर्शन', '90 मिनट'],
          ['12:30–1:30 PM', 'ISKCON प्रसाद हॉल या मधुवन रेस्टोरेंट में लंच', '1 घंटा'],
          ['2:30–4:00 PM', 'राधा रमण या राधा दामोदर मंदिर', '90 मिनट'],
          ['4:00–5:30 PM', 'प्रेम मंदिर — वास्तुकला और परिसर', '90 मिनट'],
          ['5:30–7:00 PM', 'ISKCON मंदिर आरती + प्रेम मंदिर लाइट शो', '90 मिनट'],
          ['7:00 PM', 'रात का खाना + प्रस्थान', ''],
        ]},
        { type: 'h2', text: 'नाश्ते की सिफारिश' },
        { type: 'p', text: 'बृजवासी मिठाई (द्वारकाधीश मंदिर के पास): कचौरी-सब्जी और रबड़ी — मथुरा का परंपरागत नाश्ता। बजट: ₹80–120 प्रति व्यक्ति।' },
        { type: 'h2', text: 'दोपहर: वृन्दावन (10:00 AM – 5:30 PM)' },
        { type: 'p', text: 'मथुरा से ऑटो-रिक्शा या टैक्सी से वृन्दावन जाएं (₹150–250)। बाँके बिहारी से शुरू करें — दोपहर की भीड़ से पहले पहुँचने के लिए दोपहर से पहले आएं।' },
        { type: 'h2', text: 'शाम: आरती और लाइट शो (5:30 PM – 7:00 PM)' },
        { type: 'p', text: 'ISKCON संध्या आरती (6:30 PM) वृन्दावन के सबसे आध्यात्मिक रूप से आवेशित क्षणों में से एक है। वहाँ से प्रेम मंदिर जाएं जहाँ शाम 7 बजे मुफ्त लाइट-एंड-म्यूजिक शो शुरू होता है।' },
        { type: 'tip', text: 'वृन्दावन में स्थानीय गाइड किराए पर लें (₹400–600 आधे दिन के लिए) जो संकरी गलियों में मार्गदर्शन करें और प्रत्येक मंदिर के पीछे की पौराणिक कथाएं बताएं।' },
      ],
    },
  },
  {
    slug: '84-kos-braj-yatra-guide',
    emoji: '🚶',
    featured: false,
    date: 'July 12, 2024',
    title: {
      en: '84 Kos Braj Yatra — What You Need to Know',
      hi: '84 कोस ब्रज यात्रा — जो आपको जानना चाहिए',
    },
    excerpt: {
      en: 'The sacred 84 Kos circumambulation of all Braj Mandal. Route, duration, important stops, and how to join an organized yatra.',
      hi: 'संपूर्ण ब्रज मंडल की पवित्र 84 कोस परिक्रमा। मार्ग, अवधि, प्रमुख पड़ाव और संगठित यात्रा में कैसे शामिल हों।',
    },
    category: { en: 'Pilgrimage', hi: 'तीर्थयात्रा' },
    readTime: { en: '10 min read', hi: '10 मिनट पढ़ें' },
    content: {
      en: [
        { type: 'p', text: 'The 84 Kos Braj Yatra (also called Braj Chaurasi Kos Parikrama) is one of the most ambitious pilgrimages in the Hindu tradition — a circumambulation of the entire Braj Mandal region, covering approximately 252 km (84 kos).' },
        { type: 'h2', text: 'Key Facts' },
        { type: 'table', headers: ['Detail', 'Information'], rows: [
          ['Total distance', '252 km (84 kos, where 1 kos ≈ 3 km)'],
          ['Duration on foot', '40–45 days'],
          ['Duration by vehicle', '5–7 days'],
          ['Number of sacred stops', 'Over 400 shrines across 12 districts'],
          ['Starting point', 'Mathura (Vishram Ghat or Janmabhoomi)'],
          ['Best season', 'Kartik month (Oct–Nov) or Chaitra (Mar–Apr)'],
          ['Organised yatras', 'Kartik: approximately 50,000–100,000 pilgrims per batch'],
        ]},
        { type: 'h2', text: 'The Route — Major Stops in Order' },
        { type: 'ol', items: [
          'Mathura (Vishram Ghat) — Starting point',
          'Gokul — Where Vasudeva brought infant Krishna; Raman Reti sands',
          'Mahavan — Krishna\'s early childhood; Brahmand Ghat',
          'Baldeo (Dauji) — Temple of Balarama; healing kund',
          'Govardhan — Sacred hill; Radhakund; Kusum Sarovar',
          'Barsana — Radharani\'s village; hilltop temple',
          'Nandagram — Nanda Baba\'s village',
          'Sanket — Secret meeting place of Radha-Krishna',
          'Aring — Ancient Arjuna-related site',
          'Kosi — Important dhamas for Parikrama rest',
          'Kot Baan — Near Kamyavan forest',
          'Kamyavan — Lush forest; Kameshwar Mahadev',
          'Vrindavan — Final major stop before returning to Mathura',
        ]},
        { type: 'h2', text: 'Organised Group Yatras (Kartik Parikrama)' },
        { type: 'p', text: 'The biggest batch parikramas happen in Kartik (October–November). Several organisations run free group yatras where accommodation (dharamshalas along the route) and simple meals (langar) are provided by seva organisations.' },
        { type: 'ul', items: [
          'Uttar Pradesh Braj Teertha Vikas Parishad organises the official Braj Parikrama',
          'Registration opens 1–2 months before Kartik; free for all pilgrims',
          'Medical teams travel with the group',
          'Batches leave Mathura every 2–3 days during Kartik',
          'Daily distance on foot: 8–12 km (rest stops every 3–4 km)',
        ]},
        { type: 'h2', text: 'Can I Do It By Vehicle?' },
        { type: 'p', text: 'Yes — many devotees cover the route by car/tempo in 5–7 days, stopping at each major shrine. This is recommended for elderly pilgrims. Hire a local driver from Mathura (₹3,000–5,000/day) who knows all the smaller village stops.' },
        { type: 'tip', text: 'For the foot parikrama, break-in your feet two weeks before with long daily walks. The first 3 days are typically hardest as the body adjusts. Most pilgrims find it becomes easier after Govardhan (day 4–5).' },
        { type: 'h2', text: 'What to Carry' },
        { type: 'ul', items: [
          'Lightweight backpack (15–20 kg max)',
          'Cotton clothes (3–4 sets); wool shawl for Kartik nights',
          'Comfortable walking shoes + sandals for temple entry',
          'Water bottle (refill stations at major stops)',
          'First-aid: antiseptic, bandages, antacid tablets, ORS sachets',
          'ID proof and some cash (₹5,000–10,000 for the full route)',
          'Portable mobile charger',
        ]},
      ],
      hi: [
        { type: 'p', text: '84 कोस ब्रज यात्रा हिंदू परंपरा की सबसे महत्वाकांक्षी तीर्थयात्राओं में से एक है — संपूर्ण ब्रज मंडल क्षेत्र की परिक्रमा, जिसमें लगभग 252 किमी (84 कोस) की दूरी शामिल है।' },
        { type: 'h2', text: 'मुख्य तथ्य' },
        { type: 'table', headers: ['विवरण', 'जानकारी'], rows: [
          ['कुल दूरी', '252 किमी (84 कोस, जहाँ 1 कोस ≈ 3 किमी)'],
          ['पैदल अवधि', '40–45 दिन'],
          ['वाहन से अवधि', '5–7 दिन'],
          ['पवित्र पड़ावों की संख्या', '12 जिलों में 400 से अधिक तीर्थ'],
          ['आरंभ बिंदु', 'मथुरा (विश्राम घाट या जन्मभूमि)'],
          ['सर्वोत्तम मौसम', 'कार्तिक माह (अक्टूबर–नवंबर) या चैत्र (मार्च–अप्रैल)'],
        ]},
        { type: 'h2', text: 'मार्ग — क्रम में प्रमुख पड़ाव' },
        { type: 'ol', items: [
          'मथुरा (विश्राम घाट) — आरंभ बिंदु',
          'गोकुल — जहाँ वासुदेव शिशु कृष्ण को लाए; रमण रेती',
          'महावन — कृष्ण का प्रारंभिक बचपन; ब्रह्मांड घाट',
          'बलदेव (दाऊजी) — बलराम का मंदिर',
          'गोवर्धन — पवित्र पर्वत; राधाकुंड; कुसुम सरोवर',
          'बरसाना — राधारानी का गाँव; पहाड़ी मंदिर',
          'नंदग्राम — नंद बाबा का गाँव',
          'वृन्दावन — मथुरा वापसी से पहले अंतिम प्रमुख पड़ाव',
        ]},
        { type: 'h2', text: 'संगठित समूह यात्राएं (कार्तिक परिक्रमा)' },
        { type: 'p', text: 'सबसे बड़ी बैच परिक्रमाएं कार्तिक (अक्टूबर–नवंबर) में होती हैं। कई संगठन मुफ्त समूह यात्राएं चलाते हैं जहाँ धर्मशाला में आवास और सेवा संगठनों द्वारा सरल भोजन (लंगर) प्रदान किया जाता है।' },
        { type: 'ul', items: [
          'उत्तर प्रदेश ब्रज तीर्थ विकास परिषद आधिकारिक ब्रज परिक्रमा का आयोजन करती है',
          'पंजीकरण कार्तिक से 1–2 महीने पहले खुलता है; सभी तीर्थयात्रियों के लिए निःशुल्क',
          'चिकित्सा दल समूह के साथ यात्रा करता है',
          'प्रतिदिन पैदल दूरी: 8–12 किमी (हर 3–4 किमी पर विश्राम)',
        ]},
        { type: 'tip', text: 'पैदल परिक्रमा के लिए दो सप्ताह पहले से रोज लंबी सैर करके पाँव को तैयार करें। पहले 3 दिन सबसे कठिन होते हैं। अधिकांश तीर्थयात्री गोवर्धन (दिन 4–5) के बाद इसे आसान पाते हैं।' },
      ],
    },
  },
  {
    slug: 'mathura-vrindavan-family-travel-guide',
    emoji: '👨‍👩‍👧‍👦',
    featured: false,
    date: 'June 20, 2024',
    title: {
      en: 'Mathura Vrindavan with Family — Complete Tips',
      hi: 'परिवार के साथ मथुरा वृन्दावन — संपूर्ण सुझाव',
    },
    excerpt: {
      en: 'Travelling with children or elderly parents? Here is everything you need for a comfortable, safe and spiritually enriching family trip.',
      hi: 'बच्चों या बुजुर्ग माता-पिता के साथ यात्रा कर रहे हैं? एक आरामदायक, सुरक्षित और आध्यात्मिक रूप से समृद्ध पारिवारिक यात्रा के लिए सब कुछ।',
    },
    category: { en: 'Family Travel', hi: 'पारिवारिक यात्रा' },
    readTime: { en: '7 min read', hi: '7 मिनट पढ़ें' },
    content: {
      en: [
        { type: 'p', text: 'Mathura and Vrindavan are excellent destinations for family travel — the spiritual atmosphere, the stories of Krishna that children already know, and the visual spectacle of the temples make it one of India\'s most memorable family pilgrimage destinations.' },
        { type: 'h2', text: 'Temples That Are Best for Families' },
        { type: 'ul', items: [
          'Prem Mandir — Wide open marble grounds, no crowding in most areas; children love the tableau scenes of Krishna\'s life',
          'ISKCON Vrindavan — Clean facilities, English signage, well-organised; prasad restaurant on-site',
          'Vishram Ghat boat ride — Children\'s favourite; 20-minute boat ride; clearly safe with life vests',
          'Kusum Sarovar (Govardhan) — Garden setting, peacocks, step-well; ideal for elderly who cannot walk long distances',
          'Banke Bihari — Magical but very crowded; not ideal for small children in pushchairs',
        ]},
        { type: 'h2', text: 'Accessibility for Elderly Visitors' },
        { type: 'table', headers: ['Temple', 'Wheelchair Accessible?', 'Notes'], rows: [
          ['Prem Mandir', 'Yes', 'Flat marble grounds; wheelchairs available at entrance'],
          ['ISKCON Vrindavan', 'Yes', 'Lift to main hall; ramp access throughout'],
          ['Krishna Janmabhoomi', 'Partial', 'Main shrine accessible; some inner areas have steps'],
          ['Dwarkadhish', 'No', 'Multiple flights of stairs; electric vehicle available nearby'],
          ['Banke Bihari', 'No', 'Narrow lanes; very crowded; not recommended for wheelchairs'],
          ['Vishram Ghat', 'Partial', 'Ghat has steps; riverside seating area is flat'],
        ]},
        { type: 'h2', text: 'Safe Food for Children' },
        { type: 'ul', items: [
          'ISKCON prasad (Hare Krishna restaurants): controlled preparation, clean, consistent quality',
          'Brijwasi brand sweets (Mathura peda, rabri): hygienic, reputable shops near Dwarkadhish',
          'Packaged namkeen from big shops: Haldiram\'s outlets available in Mathura',
          'Fruits from market: mangoes and guavas in season are excellent',
          'Avoid: street-side chaat, cut fruit, uncovered items — risk of stomach issues',
          'Water: carry sealed bottles or use hotel filtered water',
        ]},
        { type: 'h2', text: 'Best Crowd-Safe Timings for Families' },
        { type: 'ul', items: [
          'Weekdays (Mon–Thu) are significantly less crowded than weekends',
          'Avoid visiting during Ekadashi and Purnima — all temples are packed',
          'Best timing: 7–9 AM for Mathura temples; 3–5 PM for Vrindavan (post-afternoon break)',
          'Janmashtami, Holi, and major festivals: crowds reach 5–10 lakh — not ideal for young children',
        ]},
        { type: 'h2', text: 'Where to Stay with Family' },
        { type: 'ul', items: [
          'Mathura: Hotel Brijwasi Royal, Radisson Blu Agra (30 min drive) — family suites available',
          'Vrindavan: MVT (ISKCON guesthouse), Hotel Vrinda Heritage, Krishna Residency',
          'Budget: Dharamshalas near major temples — basic but clean; book ahead',
          'Recommended: stay in Vrindavan for the atmosphere; day-trip to Mathura',
        ]},
        { type: 'h2', text: 'Tips for Travelling with Small Children' },
        { type: 'ul', items: [
          'Carry a light carrier or sling for infants — pushchairs are impractical in narrow lanes',
          'Teach children basic temple etiquette before visiting (remove shoes, quiet voices)',
          'Make it interactive: tell Krishna stories at each location — Banke Bihari, Janmabhoomi, boat ride on Yamuna',
          'Set up a child-friendly base at your hotel between temple visits — 2-hour rest after lunch',
          'Summer: carry a portable battery fan; sun cream; hats',
        ]},
        { type: 'tip', text: 'Book a half-day family tour with a registered guide from Mathura (₹800–1,200 for 4 hours). They tailor the pace and storytelling for children and handle all logistics, so you can focus on the experience.' },
      ],
      hi: [
        { type: 'p', text: 'मथुरा और वृन्दावन परिवार के साथ यात्रा के लिए उत्कृष्ट स्थान हैं — आध्यात्मिक वातावरण, कृष्ण की कहानियाँ जो बच्चे पहले से जानते हैं, और मंदिरों का दृश्य वैभव इसे भारत के सबसे यादगार पारिवारिक तीर्थस्थलों में से एक बनाता है।' },
        { type: 'h2', text: 'परिवार के लिए सर्वोत्तम मंदिर' },
        { type: 'ul', items: [
          'प्रेम मंदिर — विशाल खुले संगमरमर के मैदान; बच्चों को कृष्ण जीवन के दृश्य पसंद आते हैं',
          'ISKCON वृन्दावन — स्वच्छ सुविधाएं, अंग्रेजी/हिंदी साइनेज, सुव्यवस्थित; प्रसाद रेस्तरां',
          'विश्राम घाट नाव यात्रा — बच्चों का पसंदीदा; 20 मिनट की नाव यात्रा',
          'कुसुम सरोवर (गोवर्धन) — बगीचा, मोर, बावड़ी; बुजुर्गों के लिए आदर्श',
          'बाँके बिहारी — जादुई लेकिन बहुत भीड़भाड़; छोटे बच्चों के लिए आदर्श नहीं',
        ]},
        { type: 'h2', text: 'बच्चों के लिए सुरक्षित भोजन' },
        { type: 'ul', items: [
          'ISKCON प्रसाद: नियंत्रित तैयारी, स्वच्छ, लगातार गुणवत्ता',
          'बृजवासी ब्रांड की मिठाइयाँ: मथुरा पेड़ा, रबड़ी; द्वारकाधीश के पास स्वच्छ दुकानें',
          'बड़ी दुकानों से पैकेज्ड नमकीन: मथुरा में हल्दीराम',
          'बचें: सड़क किनारे की चाट, कटे फल, खुले हुए सामान',
          'पानी: सीलबंद बोतलें या होटल का फ़िल्टर किया पानी',
        ]},
        { type: 'h2', text: 'परिवारों के लिए सर्वोत्तम भीड़-मुक्त समय' },
        { type: 'ul', items: [
          'सप्ताह के दिन (सोमवार–गुरुवार) सप्ताहांत की तुलना में काफी कम भीड़ होती है',
          'एकादशी और पूर्णिमा के दौरान जाने से बचें — सभी मंदिर खचाखच भरे होते हैं',
          'सर्वोत्तम समय: मथुरा के लिए सुबह 7–9 बजे; वृन्दावन के लिए दोपहर 3–5 बजे',
        ]},
        { type: 'tip', text: 'मथुरा से पंजीकृत गाइड के साथ आधे दिन का पारिवारिक दौरा बुक करें (4 घंटे के लिए ₹800–1,200)। वे बच्चों के लिए गति और कहानी-सुनाना तैयार करते हैं।' },
      ],
    },
  },
]

export function getPostBySlug(slug: string): BlogPostData | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug)
}

export function getLocalizedPost(post: BlogPostData, locale: string) {
  const lang = locale === 'hi' ? 'hi' : 'en'
  return {
    ...post,
    title:    post.title[lang],
    excerpt:  post.excerpt[lang],
    category: post.category[lang],
    readTime: post.readTime[lang],
    content:  post.content[lang],
  }
}
